#!/bin/sh
# Regenerate src/vendor/psl.js from the Public Suffix List.
#
# The list is needed to answer "are these two hostnames the same site" without
# getting it dangerously wrong. The naive alternatives both fail:
#
#   hostname.endsWith("google.com")  also matches evil-google.com
#   last two labels                  makes foo.co.uk and bar.co.uk one site
#
# Firefox exposes no eTLD+1 API to extensions, so the list has to be carried.
# Committed rather than fetched at build time, per benco-build-and-packaging.md
# §2 — and because a password manager that phones a third party to decide where
# it is safe to type a password has the wrong shape.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/src/vendor/psl.js"
src=${1:-https://publicsuffix.org/list/public_suffix_list.dat}
tmp=$(mktemp)

if [ -f "$src" ]; then cp "$src" "$tmp"; else curl -sSf -o "$tmp" "$src"; fi

date=$(grep -m1 -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}' "$tmp" || echo unknown)
rules=$(grep -v '^//' "$tmp" | grep -v '^[[:space:]]*$' | LC_ALL=C sort -u)
count=$(printf '%s\n' "$rules" | wc -l | tr -d ' ')

{
  echo "// GENERATED by tools/vendor-psl.sh — do not edit."
  echo "// Public Suffix List, $count rules, retrieved $(date -u +%Y-%m-%d)."
  echo "// Mozilla Public License 2.0: https://publicsuffix.org/list/"
  echo "//"
  echo "// Refresh occasionally. A stale list is not a security hole — an unknown"
  echo "// suffix degrades to treating the last two labels as the site, which is"
  echo "// conservative — but new TLDs will match more loosely than they should."
  echo
  echo "export const PSL_RULES = new Set(["
  printf '%s\n' "$rules" | sed "s/.*/  '&',/"
  echo "]);"
} > "$out"

echo "vendored $count rules (list dated $date) -> src/vendor/psl.js ($(wc -c < "$out") bytes)"
rm -f "$tmp"
