#!/bin/sh
# Regenerate src/vendor/argon2.js from the npm package.
#
# The extension cannot resolve a bare "hash-wasm" specifier and cannot use an
# import map — that needs an inline <script type="importmap">, which the
# extension CSP forbids. So the dependency is vendored as one ES module and
# imported by path, which Node and Firefox both resolve identically.
#
# argon2.umd.min.js is the per-algorithm bundle: 29 KB with the wasm inlined as
# base64. The full index.esm.js is 216 KB of algorithms this project never
# calls, and would still need the same treatment.
#
# The UMD wrapper finds no `exports` and no `define` inside an ES module, so it
# takes its global branch and attaches to globalThis.hashwasm. Appending the
# export below is the whole adaptation.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
src="$root/node_modules/hash-wasm/dist/argon2.umd.min.js"
out="$root/src/vendor/argon2.js"
version=$(node -p "require('$root/node_modules/hash-wasm/package.json').version")

[ -f "$src" ] || { echo "missing $src — run npm install first" >&2; exit 1; }

mkdir -p "$root/src/vendor"
{
  echo "// GENERATED by tools/vendor.sh from hash-wasm $version — do not edit."
  echo "// Upstream is MIT licensed; see LICENSE-hash-wasm.txt beside this file."
  echo
  cat "$src"
  echo
  echo "export const argon2id = globalThis.hashwasm.argon2id;"
} > "$out"

cp "$root/node_modules/hash-wasm/LICENSE" "$root/src/vendor/LICENSE-hash-wasm.txt" 2>/dev/null || true

echo "vendored hash-wasm $version -> src/vendor/argon2.js ($(wc -c < "$out") bytes)"
